# Welcome to numpy

* In this notebook we will revise numpy 

In [1]:
import numpy as np


In [2]:
print("Hello World")

Hello World


In [3]:
myarr = np.array([[3,6,9]], np.int8) 

In [4]:
myarr[0,1]

6

In [5]:
myarr.shape

(1, 3)

In [6]:
myarr.dtype

dtype('int8')

In [7]:
myarr[0,1] = 45

In [8]:
myarr

array([[ 3, 45,  9]], dtype=int8)

# Array Creation: Conversion from other Python structures 

In [9]:
listArray = np.array([[1,2,3],[2,4,6],[1,3,5]])

In [10]:
listArray

array([[1, 2, 3],
       [2, 4, 6],
       [1, 3, 5]])

In [11]:
listArray.dtype

dtype('int32')

In [12]:
listArray.size

9

In [13]:
listArray.shape

(3, 3)

**Array Creation : Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)**

In [14]:
zeros = np.zeros((2,3))

In [15]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
rng = np.arange(15)

In [17]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
rng2 = np.arange(5,15)

In [19]:
rng2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
lspace= np.linspace(1,50,10)

In [21]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [22]:
arr = np.array([[2,4,6],[1,3,5]])

In [23]:
arr

array([[2, 4, 6],
       [1, 3, 5]])

In [24]:
arr.shape

(2, 3)

In [25]:
arr= arr.reshape(3,2)

In [26]:
arr

array([[2, 4],
       [6, 1],
       [3, 5]])

In [27]:
arrr = np.arange(12)

In [28]:
arrr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
arrr.shape

(12,)

In [30]:
arrr=arrr.reshape(3,4)

In [31]:
arrr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
arrr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [34]:
ar = np.array(x)

In [35]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [36]:
ar.sum(axis=0)

array([12,  8,  9])

In [37]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [38]:
ar.ndim

2

In [39]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [40]:
one = np.array([1,3,4,588,2])

In [41]:
one.argmax()

3

In [42]:
one.argmin()

0

In [43]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [44]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [45]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [46]:
ar.argmin()

8

In [47]:
ar.argmax()

6

In [48]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [49]:
ar2 = np.array([[1,2,1],
              [4,0,6],
                [8,1,0]
              ])

In [50]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [51]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [52]:
ar.sum()

29

In [53]:
ar.max()

7

In [54]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [55]:
np.count_nonzero(ar)

8

In [56]:
print(np.__version__)

1.24.3


In [57]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [58]:
b

array([1, 2, 3, 4, 5])

In [59]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [61]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [63]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]
